lActiveMutators = [
	"""Sneaker98's MVAM Infinite""",
	"""NanoFX v2.0 BETA""",
	"""Stock Systems""",
	"""QBautostart Extension V1.0""",
	"""AI auto Warping""",
	"""Per Bridge Loading screen""",
	"""Extra Ships and Mods""",
	"""Sneaker98's Bridge Menu Scroller""",
	"""Thrusters""",
	"""BCS:TNG WalkFX KM Edition""",
	"""MLeoDaalder's Detail/Nit Fix""",
	"""Nemesis Collisions""",
	"""Advanced Power control""",
	"""Stock Ships""",
	"""BCS:TB: Silent Running""",
	"""Skinning And Damaging Tool""",
	"""Alternate Nemesis Music""",
	"""Construct Mod""",
	"""USS Frontier's GravityFX""",
	"""StarfleetOperations-Cardassia""",
	"""Allow Surrender""",
	"""Sol""",
	"""Engine Smoke (SG1)""",
	"""Advanced Technologies Pack""",
	"""Stargate Hyperdrive""",
	"""DS9FX v3.0""",
	"""BanzaiZAP SystemPack""",
	"""CJMP System Maps in Quick Battle""",
	"""Foundation Technologies""",
	"""ZMSystemPack""",
	"""Auto switch Bridge""",
	"""3E's Bridge Menu Enlarger""",
	"""Blind Firing""",
	"""BCS:TB: Emergency Repair""",
	"""BCS:TB: Targetable Plasma Streams""",
	"""New Technology System""",
	"""Planet Classification Script""",
	"""BCS:TB: Assimilation Beam""",
]
